"""New migration

Revision ID: 00360234e8a8
Revises: 12c8a76f3349
Create Date: 2023-09-15 15:26:24.071945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00360234e8a8'
down_revision = '12c8a76f3349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
